import {test,before,afterEach} from 'node:test';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import type * as Testing from '@testing-library/react';
import ShopApp from '../components/ShopApp';
import {demoProducts} from '../lib/demo';
let testing:typeof Testing;
before(async()=>{const dom=new JSDOM('<!doctype html><html><body></body></html>',{url:'http://localhost:3000',pretendToBeVisual:true});Object.assign(globalThis,{window:dom.window,document:dom.window.document,HTMLElement:dom.window.HTMLElement,Node:dom.window.Node,localStorage:dom.window.localStorage});Object.defineProperty(globalThis,'navigator',{value:dom.window.navigator,configurable:true});dom.window.scrollTo=()=>{};testing=await import('@testing-library/react');});
afterEach(()=>{testing.cleanup();localStorage.clear();window.history.replaceState({},'','/');});
const config={mode:'demo' as const,quoteAvailable:false,paymentAvailable:false,businessEmail:'',businessPhone:''};
function render(path:string){window.history.replaceState({},'',path);return testing.render(<ShopApp products={demoProducts} config={config} initialPath={path.split('?')[0]} initialQuery={path.split('?')[1]||''} staticPreview/>);}
test('pack selection survives add-to-list and cart recovers after remount',async()=>{const {fireEvent,screen,waitFor}=testing;render('/products/coffee-cup');const carton=screen.getByRole('radio',{name:/Carton/}) as HTMLInputElement;fireEvent.click(carton);fireEvent.change(screen.getByRole('spinbutton',{name:'Quantity'}),{target:{value:'2'}});fireEvent.click(screen.getByRole('button',{name:'Add to quote list'}));await waitFor(()=>assert.equal(JSON.parse(localStorage.getItem('deiva-cart-v1')||'[]')[0]?.quantity,2));assert.equal((screen.getByRole('radio',{name:/Carton/}) as HTMLInputElement).checked,true);assert.equal((screen.getByRole('spinbutton',{name:'Quantity'}) as HTMLInputElement).value,'2');fireEvent.click(screen.getByRole('link',{name:'Your list, 2 packs or cartons'}));await waitFor(()=>assert.ok(screen.getByRole('heading',{name:'Your quote list'})));assert.match(screen.getByText(/2,000 total units/).textContent||'',/2,000/);testing.cleanup();render('/cart');await waitFor(()=>assert.ok(screen.getByText(/2,000 total units/)));});
test('search matches SKU and filter choices are recorded in the URL',async()=>{const {fireEvent,screen,waitFor}=testing;render('/shop');fireEvent.change(screen.getByRole('textbox',{name:'Search products or SKU'}),{target:{value:'BOWL-750'}});fireEvent.click(screen.getByRole('button',{name:'Search'}));await waitFor(()=>assert.ok(screen.getByRole('heading',{name:'Search results'})));assert.ok(screen.getByRole('link',{name:'Kraft food bowl'}));assert.match(window.location.search,/BOWL-750/);fireEvent.change(screen.getByLabelText('Material'),{target:{value:'Plastic'}});await waitFor(()=>assert.ok(screen.getByText('No products match yet.')));assert.match(window.location.search,/material=Plastic/);});
test('quick order adds valid lines and preserves input when another SKU fails',async()=>{const {fireEvent,screen,waitFor}=testing;render('/quick-order');const text='CUP-08-P, 2\nNOT-A-SKU, 1';fireEvent.change(screen.getByLabelText('SKUs and quantities'),{target:{value:text}});fireEvent.click(screen.getByRole('button',{name:'Add valid items to list'}));await waitFor(()=>assert.ok(screen.getByText(/SKU “NOT-A-SKU” was not found/)));assert.equal((screen.getByLabelText('SKUs and quantities') as HTMLTextAreaElement).value,text);await waitFor(()=>assert.equal(JSON.parse(localStorage.getItem('deiva-cart-v1')||'[]')[0]?.quantity,2));});
test('preview enquiry reports unavailable service instead of fabricated success',async()=>{const {fireEvent,screen,waitFor}=testing;render('/wholesale');fireEvent.submit(screen.getByRole('button',{name:'Check enquiry availability'}).closest('form')!);await waitFor(()=>assert.ok(screen.getByText(/This preview does not send enquiries/)));assert.equal(screen.queryByText(/Your enquiry has been saved/),null);});
test('mobile menu control exposes navigation and private checkout is inactive',async()=>{const {fireEvent,screen}=testing;render('/checkout');assert.ok(screen.getByRole('heading',{name:'Payment is not available in this preview.'}));const menu=screen.getByRole('button',{name:'Open menu'});fireEvent.click(menu);assert.equal(screen.getByRole('button',{name:'Close menu'}).getAttribute('aria-expanded'),'true');});
