import 'server-only';
import {parse} from 'csv-parse/sync';
import {z} from 'zod';
import {rows,run,transaction} from './db';
import {HttpError} from './security';
const id=z.string().regex(/^[a-zA-Z0-9_-]{1,100}$/);
const rowSchema=z.object({product_id:id,slug:z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).max(150),name:z.string().min(2).max(200),category:z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).max(100),material:z.string().min(1).max(100),capacity:z.string().max(150),dimensions:z.string().max(200),colour:z.string().max(100),description:z.string().min(10).max(5000),image_url:z.string().max(1000).refine(s=>s.startsWith('/products/')||/^https:\/\//.test(s),'Use a committed product image or an HTTPS media URL.'),variant_id:id,sku:z.string().min(1).max(100),label:z.string().min(1).max(100),units:z.coerce.number().int().min(1).max(1000000),price_cents:z.preprocess(v=>v===''?null:v,z.coerce.number().int().min(1).max(10000000).nullable()),stock:z.preprocess(v=>v===''?null:v,z.coerce.number().int().min(0).max(10000000).nullable()),minimum:z.coerce.number().int().min(1).max(10000),increment:z.coerce.number().int().min(1).max(10000)});
export function validateImport(csv:string){let raw;try{raw=parse(csv,{columns:true,skip_empty_lines:true,trim:true,bom:true,max_record_size:10000});}catch{throw new HttpError(400,'The CSV could not be read. Check headers and quoted fields.');}if(!Array.isArray(raw)||!raw.length||raw.length>2000)throw new HttpError(400,'Import between 1 and 2,000 rows.');const errors:string[]=[];const valid:z.infer<typeof rowSchema>[]=[];const skus=new Set<string>();const variants=new Set<string>();const products=new Map<string,string>();for(let i=0;i<raw.length;i++){const parsed=rowSchema.safeParse(raw[i]);if(!parsed.success){errors.push(`Row ${i+2}: ${parsed.error.issues.map(x=>x.path.join('.')+': '+x.message).join('; ')}`);continue;}const r=parsed.data;const canonical=JSON.stringify([r.slug,r.name,r.category,r.material,r.capacity,r.dimensions,r.colour,r.description,r.image_url]);if(skus.has(r.sku.toLowerCase()))errors.push(`Row ${i+2}: duplicate SKU ${r.sku}.`);if(variants.has(r.variant_id))errors.push(`Row ${i+2}: duplicate variant ID ${r.variant_id}.`);if(products.has(r.product_id)&&products.get(r.product_id)!==canonical)errors.push(`Row ${i+2}: inconsistent details for product ${r.product_id}.`);skus.add(r.sku.toLowerCase());variants.add(r.variant_id);products.set(r.product_id,canonical);valid.push(r);}if(errors.length)throw new HttpError(400,errors.slice(0,20).join('\n'));return valid;}
export async function importCatalogue(csv:string){const input=validateImport(csv);return transaction(async c=>{for(const r of input){const slugConflicts=await rows('SELECT id,slug FROM products WHERE slug=? OR id=? FOR UPDATE',[r.slug,r.product_id],c);if(slugConflicts.some(p=>p.id!==r.product_id))throw new HttpError(400,`Product URL ${r.slug} is already assigned to another record.`);const conflicts=await rows('SELECT id,sku,reserved,product_id FROM variants WHERE sku=? OR id=? FOR UPDATE',[r.sku,r.variant_id],c);if(conflicts.some(v=>v.id!==r.variant_id||v.sku!==r.sku||v.product_id!==r.product_id))throw new HttpError(400,`SKU ${r.sku} or variant ID is already assigned to another record.`);if(r.stock!=null&&conflicts.some(v=>Number(v.reserved)>r.stock!))throw new HttpError(409,`Stock for ${r.sku} is below its active reservations.`);await run("INSERT IGNORE INTO categories(slug,name,description) VALUES(?,?, '')",[r.category,r.category.replaceAll('-',' ').replace(/\b\w/g,x=>x.toUpperCase())],c);await run("INSERT INTO products(id,slug,name,category,material,capacity,dimensions,colour,description,image_url,compatible_ids,preview) VALUES(?,?,?,?,?,?,?,?,?,?,'[]',0) ON DUPLICATE KEY UPDATE slug=VALUES(slug),name=VALUES(name),category=VALUES(category),material=VALUES(material),capacity=VALUES(capacity),dimensions=VALUES(dimensions),colour=VALUES(colour),description=VALUES(description),image_url=VALUES(image_url)",[r.product_id,r.slug,r.name,r.category,r.material,r.capacity,r.dimensions,r.colour,r.description,r.image_url],c);await run('INSERT INTO variants(id,product_id,sku,label,units,minimum,increment,price_cents,stock) VALUES(?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE label=VALUES(label),units=VALUES(units),minimum=VALUES(minimum),increment=VALUES(increment),price_cents=VALUES(price_cents),stock=VALUES(stock)',[r.variant_id,r.product_id,r.sku,r.label,r.units,r.minimum,r.increment,r.price_cents,r.stock],c);}return input.length;});}
