import 'server-only';
import {createHash,randomBytes,scryptSync,timingSafeEqual} from 'node:crypto';
import {SignJWT,jwtVerify} from 'jose';
import {rows,run} from './db';
import {siteUrl} from './config';
export class HttpError extends Error{constructor(public status:number,message:string){super(message);}}
export const digest=(value:string)=>createHash('sha256').update(value).digest('hex');
export const token=()=>randomBytes(32).toString('hex');
export function sameOrigin(request:Request){const origin=request.headers.get('origin');if(!origin||origin!==siteUrl())throw new HttpError(403,'Please submit this request from the shop.');}
export async function body(request:Request,max=100000){if(Number(request.headers.get('content-length')||0)>max)throw new HttpError(413,'The request is too large.');const raw=await request.text();if(Buffer.byteLength(raw)>max)throw new HttpError(413,'The request is too large.');try{return JSON.parse(raw);}catch{throw new HttpError(400,'Invalid request format.');}}
export function failure(error:unknown){if(error instanceof HttpError)return Response.json({error:error.message},{status:error.status});if(error&&typeof error==='object'&&'issues'in error)return Response.json({error:'Check the required fields, lengths and quantities.'},{status:400});return Response.json({error:'This service is temporarily unavailable. Your browser list has been preserved.'},{status:503});}
export async function rateLimit(request:Request,action:string,max=8,identity=''){const ip=(request.headers.get('x-forwarded-for')||request.headers.get('x-real-ip')||'unknown').split(',')[0].trim();const key=digest(action+':'+ip+':'+identity);const bucket=Math.floor(Date.now()/60000);await run('INSERT INTO request_limits(limit_key,bucket,hits) VALUES(?,?,1) ON DUPLICATE KEY UPDATE hits=hits+1',[key,bucket]);const [result]=await rows('SELECT hits FROM request_limits WHERE limit_key=? AND bucket=?',[key,bucket]);if(Number(result.hits)>max)throw new HttpError(429,'Too many attempts. Please wait a minute before trying again.');await run('DELETE FROM request_limits WHERE bucket<? LIMIT 100',[bucket-1440]);}
export function passwordMatches(password:string){const encoded=process.env.ADMIN_PASSWORD_HASH||'';const [scheme,salt,hash]=encoded.split('$');if(scheme!=='scrypt'||!salt||!/^[a-f0-9]{128}$/.test(hash||''))return false;const actual=scryptSync(password,salt,64);return timingSafeEqual(actual,Buffer.from(hash,'hex'));}
function secret(){const value=process.env.AUTH_SECRET||'';if(value.length<32)throw new HttpError(503,'Owner sign-in is not configured.');return new TextEncoder().encode(value);}
export async function createSession(){const csrf=token();const jwt=await new SignJWT({role:'owner',csrf}).setProtectedHeader({alg:'HS256'}).setIssuer('deiva-packaging').setAudience('deiva-owner').setIssuedAt().setExpirationTime('8h').sign(secret());return {jwt,csrf};}
export async function session(request:Request,mutation=false){const cookie=request.headers.get('cookie')||'';const raw=cookie.split(';').map(x=>x.trim()).find(x=>x.startsWith('deiva_owner='))?.slice(12);if(!raw)throw new HttpError(401,'Owner sign-in is required.');try{const {payload}=await jwtVerify(raw,secret(),{issuer:'deiva-packaging',audience:'deiva-owner',algorithms:['HS256']});if(payload.role!=='owner'||typeof payload.csrf!=='string')throw new Error('Invalid session.');if(mutation){sameOrigin(request);if(request.headers.get('x-csrf-token')!==payload.csrf)throw new HttpError(403,'Your session could not be verified. Please sign in again.');}return {csrf:payload.csrf};}catch(e){if(e instanceof HttpError)throw e;throw new HttpError(401,'Your session has expired. Please sign in again.');}}
export function sessionCookie(jwt:string,expired=false){return `deiva_owner=${jwt}; HttpOnly; Path=/; SameSite=Strict; Max-Age=${expired?0:28800}${siteUrl().startsWith('https:')?'; Secure':''}`;}
