import {z} from 'zod';
export const lineSchema=z.object({variantId:z.string().min(1).max(100),quantity:z.number().int().min(1).max(10000)});
export const linesSchema=z.array(lineSchema).max(100);
export const enquirySchema=z.object({name:z.string().trim().min(2).max(100),business:z.string().trim().max(150).default(''),email:z.email().max(200),phone:z.string().trim().max(40).default(''),postcode:z.string().regex(/^\d{4}$/),notes:z.string().trim().min(10).max(5000),marketing:z.boolean().default(false),website:z.string().max(0).default(''),lines:linesSchema.default([])});
export const checkoutSchema=z.object({name:z.string().trim().min(2).max(100),email:z.email().max(200),address:z.string().trim().min(3).max(200),suburb:z.string().trim().min(2).max(100),state:z.enum(['VIC','NSW','QLD','SA','WA','TAS','ACT','NT']),postcode:z.string().regex(/^\d{4}$/),deliveryId:z.string().min(1).max(100),lines:linesSchema.min(1)});
export const deliverySchema=z.array(z.object({id:z.string().min(1).max(100),label:z.string().min(1).max(200),postcodes:z.array(z.string().regex(/^\d{4}$/)).min(1),chargeCents:z.number().int().min(0).max(1000000),method:z.enum(['delivery','collection']),collectionAddress:z.string().max(300).optional()})).max(100);
export function deliveryOptions(postcode:string){const rules=deliverySchema.parse(JSON.parse(process.env.DELIVERY_RULES_JSON||'[]'));return rules.filter(r=>r.postcodes.includes(postcode)&&!(r.method==='collection'&&!r.collectionAddress));}
export function mergeLines(lines:z.infer<typeof linesSchema>){const map=new Map<string,number>();for(const l of lines){const q=(map.get(l.variantId)||0)+l.quantity;if(q>10000)throw new Error('Quantity exceeds the limit.');map.set(l.variantId,q);}return [...map].sort(([a],[b])=>a.localeCompare(b)).map(([variantId,quantity])=>({variantId,quantity}));}
export function gstFromGross(cents:number,rate:number){if(!Number.isSafeInteger(cents)||cents<0||![0,1000].includes(rate))throw new Error('Invalid tax calculation.');return rate===0?0:Math.round(cents/11);}
export function csvSafe(value:unknown){const text=String(value??'');const safe=/^[=+@\-\t\r]/.test(text)?"'"+text:text;return '"'+safe.replaceAll('"','""')+'"';}
