import type {Metadata} from 'next';
import {notFound} from 'next/navigation';
import ShopApp from '../../components/ShopApp';
import {catalogue,publicCategories} from '../../lib/catalogue';
import {publicConfig,siteUrl,commerceMode} from '../../lib/config';
import {categories} from '../../lib/demo';
export const dynamic='force-dynamic';
const titles:Record<string,string>={shop:'Shop Packaging',search:'Product Search',cart:'Your Cart',checkout:'Guest Checkout','order-confirmation':'Order Status',wholesale:'Wholesale Packaging Quotes',about:'About Deiva Packaging',contact:'Contact',faqs:'FAQs',delivery:'Delivery & Collection',returns:'Returns',privacy:'Privacy Information',terms:'Terms','packaging-guide':'Packaging Guide','quick-order':'SKU Quick Order',admin:'Owner Access'};
type Props={params:Promise<{slug:string[]}>;searchParams:Promise<Record<string,string|string[]|undefined>>};
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const path='/'+slug.join('/');let title=titles[slug[0]]||'Packaging Supplies';let description='Packaging supplies and business ordering information from Deiva Packaging, Melbourne.';let product;try{if(slug[0]==='products')product=(await catalogue()).find(p=>p.slug===slug[1]);}catch{}if(product){title=product.name;description=product.description;}if(slug[0]==='category'){let list=categories;try{list=await publicCategories();}catch{}const c=list.find(c=>c.slug===slug[1]);title=c?.name||title;description=c?.description||description;}const privateRoute=['search','cart','checkout','order-confirmation','admin'].includes(slug[0]);return {title,description,alternates:{canonical:siteUrl()+path},robots:privateRoute||commerceMode()==='demo'||process.env.SITE_INDEXABLE!=='true'?{index:false,follow:false}:{index:true,follow:true},openGraph:{title,description,type:'website',...(product&&!product.preview?{images:[new URL(product.image,siteUrl()).href]}:{})}};}
export default async function Page({params,searchParams}:Props){const {slug}=await params;const search=await searchParams;let products:import('../../lib/types').Product[];const config=publicConfig();let categoryList:import('../../lib/types').Category[];try{[products,categoryList]=await Promise.all([catalogue(),publicCategories()]);}catch{products=[];categoryList=[];config.catalogueUnavailable=true;}if((titles[slug[0]]&&slug.length!==1)||(['products','category'].includes(slug[0])&&slug.length!==2)||(!titles[slug[0]]&&!['products','category'].includes(slug[0])))notFound();if(slug[0]==='products'&&!config.catalogueUnavailable&&!products.find(p=>p.slug===slug[1]))notFound();if(slug[0]==='category'&&!categoryList.find(c=>c.slug===slug[1]))notFound();const query=new URLSearchParams(Object.entries(search).flatMap(([k,v])=>Array.isArray(v)?v.map(x=>[k,x]):v?[[k,v]]:[])).toString();const product=slug[0]==='products'?products.find(p=>p.slug===slug[1]):undefined;const structured=product&&!product.preview?{'@context':'https://schema.org','@type':'Product',name:product.name,description:product.description,image:new URL(product.image,siteUrl()).href,sku:product.variants[0]?.sku,...(product.variants[0]?.priceCents!=null?{offers:{'@type':'Offer',priceCurrency:'AUD',price:(product.variants[0].priceCents/100).toFixed(2),url:siteUrl()+'/products/'+product.slug}}:{})}:null;return <>{structured&&<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structured).replace(/</g,'\\u003c')}}/>}<ShopApp products={products} categoryList={categoryList} config={config} initialPath={'/'+slug.join('/')} initialQuery={query}/></>;}
