import {randomUUID} from 'node:crypto';
import {commerceMode} from '../../../lib/config';
import {catalogue} from '../../../lib/catalogue';
import {run} from '../../../lib/db';
import {body,failure,HttpError,rateLimit,sameOrigin} from '../../../lib/security';
import {enquirySchema} from '../../../lib/validation';
import {sendBusinessEmail} from '../../../lib/notifications';
export const runtime='nodejs';
export async function POST(request:Request){try{sameOrigin(request);if(commerceMode()==='demo')throw new HttpError(503,'The preview does not send enquiries. Download your list instead.');const data=enquirySchema.parse(await body(request));await rateLimit(request,'enquiry',5,data.email.toLowerCase());const products=await catalogue();const lines=data.lines.map(line=>{const product=products.find(p=>p.variants.some(v=>v.id===line.variantId));const variant=product?.variants.find(v=>v.id===line.variantId);if(!product||!variant)throw new HttpError(400,'An item in your list is unavailable. Please review it.');if(line.quantity<variant.minimum||(line.quantity-variant.minimum)%variant.increment)throw new HttpError(400,'Check your pack quantities and minimum order.');return {sku:variant.sku,name:product.name,label:variant.label,units:variant.units,quantity:line.quantity};});const id=randomUUID();const reference='DQ-'+id.slice(0,8).toUpperCase();await run('INSERT INTO enquiries(id,reference,customer_name,business_name,customer_email,phone,postcode,notes,lines_snapshot,marketing_consent) VALUES(?,?,?,?,?,?,?,?,?,?)',[id,reference,data.name,data.business,data.email,data.phone,data.postcode,data.notes,JSON.stringify(lines),data.marketing?1:0]);const notification=await sendBusinessEmail('Packaging enquiry '+reference,`Reference: ${reference}\nName: ${data.name}\nBusiness: ${data.business}\nEmail: ${data.email}\nPostcode: ${data.postcode}\nNotes: ${data.notes}\nProducts: ${lines.map(l=>`${l.sku}: ${l.quantity} ${l.label}`).join(', ')}`);await run('UPDATE enquiries SET notification_status=? WHERE id=?',[notification,id]);return Response.json({reference,saved:true,notification},{status:201});}catch(e){return failure(e);}}
